CREATE TABLE `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderNumber` varchar(255) NOT NULL,
  `userId` int(11) DEFAULT NULL,
  `customerName` varchar(255) NOT NULL,
  `customerDni` varchar(255) NOT NULL,
  `customerEmail` varchar(255) DEFAULT NULL,
  `customerPhone` varchar(255) DEFAULT NULL,
  `items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`items`)),
  `subtotal` decimal(10,2) NOT NULL,
  `shipping` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total` decimal(10,2) NOT NULL,
  `paymentMethod` varchar(255) NOT NULL DEFAULT 'CARD',
  `paymentStatus` varchar(255) NOT NULL DEFAULT 'PENDING',
  `stripePaymentId` varchar(255) DEFAULT NULL,
  `orderStatus` varchar(255) NOT NULL DEFAULT 'PENDING',
  `shippingAddress` text NOT NULL,
  `notes` text DEFAULT NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `status` varchar(255) NOT NULL DEFAULT 'PENDIENTE',
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_59b0c3b34ea0fa5562342f2414` (`orderNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
